name: Release

on:
    push:
      tags:
        - 'v*'

jobs:
    clojars:
        runs-on: ubuntu-latest
        environment: env
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4
            - uses: "DeLaGuardo/setup-clojure@12.5"
              with:
                cli: "1.11.1.1139"
            - name: deploy
              env:
                CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
                CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
              run: |
                clojure -M:dev --report stderr -m com.moclojer.tools.build && \
                clojure -X:deploy-clojars
